version: "3.7"
services:
  web-server:
    container_name: web-server
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ./docroot/:/var/www/html
      #- .vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8080:80

  mysql-server:
    image: mysql:5.7.32
    hostname: mysql.oxid
    container_name: database
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oxid
      MYSQL_USER: oxid
      MYSQL_PASSWORD: oxid

  phpmyadmin:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: database
      #PMA_PASSWORD: root
    ports:
      - 5000:80
    depends_on:
      - mysql-server
      - web-server

volumes:
  mysql-data: