version: "3.7"
services:
  web-server:
    container_name: web-server
    build:
      dockerfile: ./config/docker/php/php.Dockerfile
      context: .
    restart: always
    volumes:
      - ./docroot/:/var/www/html
      - ./config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8088:80
      - 9999:9000
    networks:
      - web
    # this is needed for xdebug, to get the right ip address in etc/hosts. see https://github.com/docker/for-linux/issues/264
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql-server:
    image: mysql:5.7.32
    hostname: mysql.oxid
    container_name: database
    restart: always
    ports:
      - 3308:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oxid
      MYSQL_USER: oxid
      MYSQL_PASSWORD: oxid
    networks:
      - web
    extra_hosts:
      - host.docker.internal:host-gateway

  phpmyadmin:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - 5000:80
    depends_on:
      - mysql-server
      - web-server
    networks:
      - web
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-data:

networks:
  web:
    external: false